### ISSUE TITLE
Indexing throws an NPE in some cases

### ISSUE THREAD

**Issue by vmuzikar** [smallrye/jandex#338]
Particularly, the newest Oracle JDBC driver (`com.oracle.database.jdbc:ojdbc11:23.3.0.23.09`) can't be indexed. For reproducer please see: https://github.com/vmuzikar/reproducers/tree/main/jandex-oracle-bug

### Context
Keycloak ran into this issue when "sideloading" the driver leveraging `quarkus.package.user-providers-directory` Quarkus option since in some cases we can't include the driver with the distribution. We managed to narrow down the issue to a potential Jandex bug. Seems that sometimes the [field signature](https://github.com/smallrye/jandex/blob/468cd083b9461f795cd374aa19bd269d42eab738/core/src/main/java/org/jboss/jandex/Indexer.java#L1804) is not decoded correctly. I haven't investigated further.

**Comment by Ladicek** [comment]
Interesting. I will take a look next week, thanks for the reproducer!

**Comment by Ladicek** [comment]
OK, this is interesting. The class in question (`oracle.jdbc.proxy.oracle$1jdbc$1driver$1AbstractShardingCallableStatement$2oracle$1jdbc$1internal$1OracleCallableStatement$$$Proxy`) has a field called `cached` of type `boolean`. The class file entry for that field contains the `Signature` attribute, which encodes the generic signature of a program element.

The Jandex parser of generic signatures closely follows the grammar from JVM Specification (see [4.7.9.1. Signatures](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-4.html#jvms-4.7.9.1)). That grammar specifically says:

```
FieldSignature:
  ReferenceTypeSignature
```

That is, field signatures are supposed to be signatures of reference types. But the signature of the `cached` field is `Z` -- a signature of a primitive type.

It seems clear that the given version of the Oracle JDBC driver contains invalid bytecode, but I take pride in Jandex being able to handle errors like this gracefully. And the fix is simple.

**Comment by Ladicek** [comment]
I'll release 3.1.6 today. Since this is a micro release, merging into Quarkus typically takes just a few days. Backporting to 3.6 should be doable; I'm not sure about 3.2.
